### ISSUE TITLE
Kyverno Adapter: Occurs Index Out of Range

### ISSUE THREAD

**Issue by b0m313** [5GSEC/nimbus#98]
In the kyverno policy applied by default, OwnerReferences was empty, causing an index out of range error when trying to access the first element.

When trying to access kcp.OwnerReferences[0], the issue occurred because the OwnerReferences slice could be empty, but we tried to access it directly without checking.

<img width="1135" alt="kyvernopol" src="https://github.com/5GSEC/nimbus/assets/76231561/60cfc998-401e-4318-9acb-5b8dcb2a8f95">

<img width="1135" alt="error" src="https://github.com/5GSEC/nimbus/assets/76231561/cae4ec26-0123-4814-9fe1-79e6e63e14a9">

**Comment by VedRatan** [comment]
Hi @b0m313 could you please tell me the steps to reproduce this error?

**Comment by anurag-rajawat** [comment]
I can reproduce this, thanks @b0m313 for opening the ticket!

> When trying to access kcp.OwnerReferences[0], the issue occurred because the OwnerReferences slice could be empty

Right.

Here is the root cause.
https://github.com/5GSEC/nimbus/blob/d6cf41614c9833c645f015dcd4ba148aaad11d11/pkg/adapter/nimbus-kyverno/manager/manager.go#L271

## To reproduce
1. Run any adapter,
2. Create a policy by hand i.e., without any owners,
3. Apply a SI & SIB

and then the adapter crashes due to accessing the first element of empty ownerrefs slice.
